server:
  port: 9027
spring:
  boot:
    admin:
      client:
        username: admin
        password: admin
        url: http://localhost:8080
        api-path: /instances
        prefer-ip: true
  application:
    name: standing-order
  zipkin:
    enabled: false
  sleuth:
    async:
      configurer:
        enabled: true

  standing-order-datasource:
    username: MT
    password: kjio0988
    jdbcUrl: jdbc:oracle:thin:@//172.30.41.22:1521/offpayapdb1
    driver-class-name: oracle.jdbc.OracleDriver
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hbm2ddl-auto: update
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    user: MT
    password: kjio0988
    schemas: MT
    baseline-on-migrate: true
    url: jdbc:oracle:thin:@//172.30.41.22:1521/offpayapdb1
    locations: classpath:db/migration

management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      slo:
        http:
          server:
            requests: 1s,5s,30s
    enable:
      tomcat: false
      process: false
      system: false
      jdbc: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric,env,httptrace,loggers
  health:
    show-details: always

logging:
  level:
    root: INFO
  file:
    name: ./logs/standing-order.log
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      file-name-pattern: .logs/payment-order-%d{yyyy-MM-dd}.%i.log

secretKeyLocation: /opt/configs

feign:
  client:
    eb-url: https://eb.bmi.ir
    baam-url: https://www.bmi.ir
    aggregation-url: 172.30.43.12:9095
    tan-url: 192.168.53.58:9080
    pooya-integration-url: 192.168.52.106:9383
    isc-integration-url: 192.168.53.58:9023
    sso-url: 192.168.53.58:9080
    payment-order-url: http://localhost:9022
    scheduler-url: http://localhost:9026
    iban-url: 192.168.53.23
    iban-token: IGD123654
    transaction-authorization-url: 192.168.53.58:9029

sso:
  grant-type: client_credentials
  scopes: transaction
  authorization: Basic a2V5OnNlY3JldA==

bmi:
  oauth2:
    excluded-urls: /api/agreements/audit,/v3/api-docs/**,/swagger-ui/**:*,/h2/**:*,/swagger-ui.html:*,/webjars/**:*,/v2/**:*,/swagger-resources/**:*,/actuator/**:*,/actuator/prometheus/**:*,/trace/**:*,/enterprisebaamapi/h2/**:*,/enterprisebaamapi/swagger-ui.html:*,/enterprisebaamapi/webjars/**:*,/enterprisebaamapi/v2/**:*,/enterprisebaamapi/swagger-resources/**:*,/enterprisebaamapi/actuator/**:*,/enterprisebaamapi/actuator/prometheus/**:*,/enterprisebaamapi/trace/**:*,/applications/**
  audit:
    advertised:
      listeners: 192.168.53.58:9090
      host:
        name: 0.0.0.0
    spring:
      kafka:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        bootstrap-servers: kafka:9092
        consumer:
          services: 192.168.53.58:8585/consumer


